project:
  type: book
  preview:
    port: 4200

book:
  title: "Climate Risk Assessment and Management"
  author: "James Doss-Gollin"
  page-footer:
    left: |
      <span class="faux-block">{{< fa brands creative-commons >}} {{< var years >}} [{{< var author >}}](https://orcid.org/{{< var orcid >}})</span>
      <span class="faux-block">
    center: |
      All content licensed under [{{< fa brands creative-commons >}} {{< fa brands creative-commons-by >}} Creative Commons CC BY 4.0](https://creativecommons.org/licenses/by/4.0/)</span>

    right: |
      <span class="faux-block">Made with Julia and [Quarto](https://quarto.org/).</span>
      <span class="faux-block">[View the source at {{< fa brands github >}} GitHub]({{< var github-url >}})</span>
    
  chapters:
    - index.qmd
    - chapters/preface.qmd
    - chapters/resources.qmd
    - part: "Part I: Foundations"
      chapters:
        - chapters/fundamentals/index.qmd
        - chapters/fundamentals/probability-stats.qmd
        - chapters/fundamentals/optimization.qmd
        - chapters/fundamentals/monte-carlo.qmd
        - chapters/fundamentals/ml-nonparametric.qmd
        - chapters/fundamentals/spatiotemporal.qmd
        - chapters/fundamentals/model-comparison.qmd
    - part: "Part II: Hazard Assessment"
      chapters:
        - chapters/hazard/index.qmd
        - chapters/hazard/climate-science.qmd
        - chapters/hazard/extremes.qmd
        - chapters/hazard/downscaling-bias-correction.qmd
        - chapters/hazard/perturbations.qmd
        - chapters/hazard/generators.qmd
        - chapters/hazard/sampling.qmd
        - chapters/hazard/model-chains.qmd
    - part: "Part III: Risk Management"
      chapters:
        - chapters/risk/index.qmd
        - chapters/risk/exposure-vulnerability.qmd
        - chapters/risk/expectations-cost-benefit.qmd
        - chapters/risk/policy-search.qmd
        - chapters/risk/risk-transfer.qmd
        - chapters/risk/deep-uncertainty.qmd
        - chapters/risk/robustness.qmd
        - chapters/risk/adaptive.qmd
        - chapters/risk/social-science.qmd

    - part: "Computational Case Studies"
      chapters: 
        - "notebooks/index.qmd"
        - "notebooks/block-maxima.qmd"
        - "notebooks/lake-problem.qmd"
        - "notebooks/mosquitos.qmd"
        - "notebooks/nonstationary-gev-fooled.qmd"
        - "notebooks/sewells-point.qmd"

    - chapters/references.qmd

  appendices: 
    - "chapters/appendices/julia.qmd"
    - "chapters/appendices/software.qmd"
    - "chapters/appendices/llm.qmd"
  
  search:
    location: sidebar
    type: textbox

  sidebar:
    collapse-level: 1
    footer: |
      Chapter titles indicate their **status:**
      🚧 Planning, 📝 Draft, ✏️ Revision, 🎯 Ready.


bibliography: references.bib

# Book-level citation metadata
citation:
  type: book
  title: "Climate Risk Assessment and Management"
  author: "James Doss-Gollin"
  url: "https://jamesdossgollin.me/teaching/climate-risk-management-book/"
  issued: "2025"
  publisher: "Self-published"
  license: "CC BY-SA 4.0"
google-scholar: true

format:
  html:
    theme: flatly
    code-overflow: wrap
    anchor-sections: true
    callout-appearance: simple
    reference-location: section
    citations-hover: true
    code-annotations: hover
    code-line-numbers: true
    html-math-method: mathjax
    date-format: iso
    notebook-links: true

glossary:
  path: _glossary.yml
  popup: hover
  show: true

# execution options
execute:
  freeze: true
  cache: true
  jupyter: julia-1.11