project:
  type: book
  preview:
    port: 4200

book:
  title: "Hydroclimate Risk Assessment and Management"
  author: "James Doss-Gollin"
  date: "2/19/2025"
  page-footer:
    left: |
      <span class="faux-block">{{< fa brands creative-commons >}} {{< var years >}} [{{< var author >}}](https://orcid.org/{{< var orcid >}})</span>
      <span class="faux-block">
    center: |
      All content licensed under [{{< fa brands creative-commons >}} {{< fa brands creative-commons-by >}} Creative Commons CC BY 4.0](https://creativecommons.org/licenses/by/4.0/)</span>

    right: |
      <span class="faux-block">Made with Julia and [Quarto](https://quarto.org/).</span>
      <span class="faux-block">[View the source at {{< fa brands github >}} GitHub]({{< var github-url >}})</span>
    
  chapters:
    - index.qmd
    - author.qmd
    - uncertainty.qmd
    - part: "Part I: Fundamentals"
      chapters:
        - chapters/fundamentals/intro.qmd
        - chapters/fundamentals/probability-stats.qmd
        - chapters/fundamentals/inference.qmd
        - chapters/fundamentals/bayes.qmd
        - chapters/fundamentals/ml.qmd
        - chapters/fundamentals/nonparametric.qmd
        - chapters/fundamentals/time-series.qmd
        - chapters/fundamentals/multidimensional.qmd
        - chapters/fundamentals/spatial.qmd
        - chapters/fundamentals/model-comparison.qmd
        - chapters/fundamentals/sensitivity.qmd
        - chapters/fundamentals/climate-science.qmd
    - part: "Part II: Hydroclimate Extremes and Catastrophes"
      chapters:
        - chapters/hazard/intro.qmd
        - chapters/hazard/extremes.qmd
        - chapters/hazard/downscaling-bias-correction.qmd
        - chapters/hazard/perturbations.qmd
        - chapters/hazard/generators.qmd
        - chapters/hazard/sampling.qmd
        - chapters/hazard/surrogate-models.qmd
    - part: "Part III: Climate Risk Management"
      chapters:
        - chapters/risk/intro.qmd
        - chapters/risk/risk.qmd
        - chapters/risk/expectations-cost-benefit.qmd
        - chapters/risk/policy-search.qmd
        - chapters/risk/robustness.qmd
        - chapters/risk/cascading.qmd
        - chapters/risk/adaptive.qmd
        - chapters/risk/risk-transfer.qmd
        - chapters/risk/equity-values.qmd
        - chapters/risk/stakeholders.qmd
    - references.qmd

    - part: "Computational Notebooks"
      chapters: 
        - "notebooks/mosquitos.qmd"
        - "notebooks/block-maxima.qmd"
        - "notebooks/sewells-point.qmd"

  search:
    location: sidebar
    type: textbox

  sidebar:
    collapse-level: 1

bibliography: references.bib

format:
  html:
    theme: flatly
    code-overflow: wrap
    anchor-sections: true
    callout-appearance: simple
    reference-location: section
    citations-hover: true
    code-annotations: hover
    code-line-numbers: true
    html-math-method: mathjax
    date-format: "ddd., MMM. D"
    notebook-links: true

glossary:
  path: _glossary.yml
  popup: click
  show: true

# use Julia
kernel: julia-1.11

# execution options
execute:
  freeze: auto  
  cache: true

citation: true